name: Build FFmpeg Encoder Plugin with Static Linking

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v5

    - name: Dependencies
      run: |
        sudo apt update
        sudo apt install -y git build-essential nasm cmake libnuma-dev liblzma-dev libbz2-dev libx265-dev autoconf \
          automake build-essential cmake libass-dev libgnutls28-dev libtool libva-dev meson ninja-build pkg-config \
          yasm zlib1g-dev
        
    - name: Build X264
      run: |
        mkdir ffmpeg_sources
        cd ffmpeg_sources
        git clone --depth 1 https://code.videolan.org/videolan/x264.git
        cd x264
        ./configure --prefix="../../ffmpeg" --enable-static --enable-pic
        make -j ${nproc}
        make install
        
    - name: Build X265
      run: |
        cd ffmpeg_sources
        git clone --depth 1 https://bitbucket.org/multicoreware/x265_git.git x265
        cd x265/build/linux
        
        mkdir 10bit && cd 10bit
        cmake ../../../source \
          -DHIGH_BIT_DEPTH=ON \
          -DEXPORT_C_API=OFF \
          -DENABLE_SHARED=OFF \
          -DENABLE_CLI=OFF
        cmake --build . -j ${nproc}
        cd ..
        
        ln -sf 10bit/libx265.a libx265_main10.a
        cmake ../../source \
          -DCMAKE_INSTALL_PREFIX="../../../../ffmpeg" \
          -DENABLE_SHARED=off -DEXTRA_LINK_FLAGS=-L. \
          -DEXTRA_LIB="x265_main10.a" \
          -DLINKED_10BIT=ON 
        cmake --build . -j ${nproc}
        
        mv libx265.a libx265_main.a
        ar -M <<EOF
        CREATE libx265.a
        ADDLIB libx265_main.a
        ADDLIB libx265_main10.a
        SAVE
        END
        EOF
        
        cmake --install .
        
    - name: Build SVT-AV1
      run: |
        cd ffmpeg_sources
        git clone --depth 1 https://gitlab.com/AOMediaCodec/SVT-AV1.git
        mkdir -p SVT-AV1/build
        cd SVT-AV1/build
        cmake -DCMAKE_INSTALL_PREFIX="../../../ffmpeg" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ..
        cmake --build . -j ${nproc}
        cmake --install .
        
    - name: Install nv-codec-headers
      run: |
        cd ffmpeg_sources
        git clone --depth 1 --branch sdk/12.0 https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
        cd nv-codec-headers
        make
        sudo make install
        
    - name: Build FFmpeg
      run: |
        cd ffmpeg_sources
        git clone --branch n8.1 https://git.ffmpeg.org/ffmpeg.git
        cd ffmpeg
        PKG_CONFIG_PATH="../../ffmpeg/lib/pkgconfig" ./configure \
          --prefix="../../ffmpeg" \
          --pkg-config-flags="--static" \
          --extra-cflags="-I../../ffmpeg/include" \
          --extra-ldflags="-L../../ffmpeg/lib" \
          --extra-libs="-lnuma" \
          --arch=amd64 \
          --disable-all \
          --enable-static \
          --enable-avcodec \
          --enable-swscale \
          --enable-swresample \
          --enable-avutil \
          --enable-gpl \
          --enable-encoder=libx264,libx265,h264_vaapi,hevc_vaapi,av1_vaapi,libsvtav1,h264_nvenc,hevc_nvenc,av1_nvenc,aac \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libsvtav1 \
          --enable-nvenc \
          --disable-vdpau
        make -j ${nproc}
        make install
        
    - name: Build FFmpeg Encoder Plugin
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j ${nproc}

    - name: Create bundle
      run: |
        mkdir -p bundle/ffmpeg_encoder_plugin.dvcp.bundle/Contents/Linux-x86-64
        cp build/ffmpeg_encoder_plugin.dvcp bundle/ffmpeg_encoder_plugin.dvcp.bundle/Contents/Linux-x86-64

    - uses: actions/upload-artifact@v4
      with:
        name: ffmpeg_encoder_plugin.dvcp.bundle
        path: bundle/
